### ISSUE TITLE
Importing reconciled CSV into Virtuoso

### ISSUE THREAD

**Issue by Yueqiao12Zhang** [DDMAL/linkedmusic-datalake#43] opened 2024-05-15 16:29 UTC
This issue is related to the issue [https://github.com/DDMAL/linkedmusic-datalake/issues/40](url). In this old issue, a simple script is made for converting a reconciled CSV file with a single subject into a turtle format RDF file. This new issue is made to enhance the script to make it compatible with reconciled CSV files with multiple and complex ER schema.

**Comment by dchiller** [comment] 2024-05-15 16:39
@Yueqiao12Zhang Just a thought...consider breaking this into multiple issues. I imagine there is a lot of work that would go into resolving each of those 3 steps -- could you forsee finishing this issue with a week of work? If not, I think better to split into smaller issues and PRs.

**Comment by Yueqiao12Zhang** [comment] 2024-05-15 16:42
Ok. The description is changed.

**Comment by Yueqiao12Zhang** [comment] 2024-05-15 17:13
5/15: 
- Fixes on the single-subject processing script.
- New task: making the script compatible with complex ER schema. 

To do:
- Improve on the time cost of the algorithm by a path-finding algorithm (?)
- Write a ReadMe file that clearly demonstrates how to write the mapper file based on a given ER schema.

**Comment by fujinaga** [comment] 2024-05-15 17:21
Can you put a hold on these tasks?
I don't know what this ER schema is. You can explain this to me on Friday.

Can you work on importing some MusicBrainz data then reconcile it using OpenRefine? Make an issue for that.

**Comment by ahankinson** [comment] 2024-05-15 18:09
Avoid an ER schema (Entity Relationship Diagram?). That is the antithesis of what you’re trying to do here.

You want to normalize the data on the way *out* not the way *in*. Dump things in as you get them, and don’t worry about trying to standardize different databases to the same structure. It won’t work, and you could spend years on it.

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 13:12
> Can you put a hold on these tasks? I don't know what this ER schema is. You can explain this to me on Friday.
> 
> Can you work on importing some MusicBrainz data then reconcile it using OpenRefine? Make an issue for that.

No problem!

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 13:22
> > Avoid an ER schema (Entity Relationship Diagram?). That is the antithesis of what you’re trying to do here.
> > You want to normalize the data on the way _out_ not the way _in_. Dump things in as you get them, and don’t worry about trying to standardize different databases to the same structure. It won’t work, and you could spend years on it.
> 
> My idea is that when we receive a new CSV full of data and an Entity Relationship Diagram of that database, we write a mapper file according to that ER diagram. Then we can just run the script to get the turtle format file and upload it to Virtuoso. If we do not write the mapper according to the ER diagram, and if the raw CSV file contains a nested relation (has more than one subject), then how can we change it to a turtle file?

For example, we have 3 columns in the CSV file:
ID,Source,Source_description
If Source is an attribute of ID and Source_description is an attribute of Source, we should be clear which attribute belongs to which subject.

**Comment by fujinaga** [comment] 2024-05-16 14:00
I still don't understand what the issue is. Let's talk about it tomorrow.

**Comment by ahankinson** [comment] 2024-05-16 14:02
> ...Entity Relationship Diagram of that database..

The purpose of almost all database that run websites is to make the software run, not to model the things you are trying to represent to humans. 

If you got an ERD of a Drupal database, it would be almost meaningless for any other purpose than to make Drupal work, since the purpose is to model the data Drupal needs, not to model the data that you're trying to represent. In other words, you would get a dump of nodes, fields, datatypes, etc. rather than an ERD of chants and sources.

**Comment by ahankinson** [comment] 2024-05-16 14:14
> ID,Source,Source_description
> If Source is an attribute of ID and Source_description is an attribute of Source, we should be clear which attribute belongs to which subject.

Your URIs will determine this. 
In triples:

```
<https://example.com/source/[id]  rdf:type http://namespace.com/type/Source>
<https://example.com/source/[id]  nnn:description "My description">
```

**Comment by ahankinson** [comment] 2024-05-16 14:18
You could post an example of the triples you're generating from the CSV so that we could review it...

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 14:22
> > ID,Source,Source_description
> > If Source is an attribute of ID and Source_description is an attribute of Source, we should be clear which attribute belongs to which subject.
> 
> Your URIs will determine this. In triples:
> 
> ```
> <https://example.com/source/[id]  rdf:type        http://namespace.com/type/Source>
> <https://example.com/source/[id]  nnn:description "My description">
> ```

Ok, which one is correct?
```
<https://namespace1.com/id/1>     rdf:type                <https://namespace2.com/id>
<https://namespace1.com/id/1>     wdt:source           <https://example.com/source/A>
<https://example.com/source/A>     rdf:type              <https://namespace2.com/source>
<https://example.com/source/A>     wdt:description  "My description"
```
Or
`
<https://namespace1.com/id/1>     rdf:type                <https://namespace2.com/id>
<https://namespace1.com/id/1>     wdt:source           <https://example.com/source/A>
<https://namespace1.com/id/1>     wdt:description    "My description"
`

**Comment by ahankinson** [comment] 2024-05-16 14:31
```
<https://example.com/source/A>   rdf:type                <https://namespace2.com/source>
<https://example.com/source/A>   wdt:description    "My description"
```

I would expect this one. I'm not sure where `<https://namespace1.com/id/1>` comes from in your example, though.

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 14:33
> For example, we have 3 columns in the CSV file:
> ID,Source,Source_description
> If Source is an attribute of ID and Source_description is an attribute of Source, we should be clear which attribute belongs to which subject.

We have 3 columns in this CSV file. ID is the key attribute of each row. Source is an attribute of ID. Source_description is an attribute of Source, but not ID.

**Comment by ahankinson** [comment] 2024-05-16 14:34
Here's an example of some source RDF we have for RISM: 

https://rism.online/apero/?url=https://rism.online/sources/800272224&format=n-triples

And here's the same document in Turtle:

https://rism.online/apero/?url=https://rism.online/sources/800272224&format=turtle

**Comment by ahankinson** [comment] 2024-05-16 14:35
>  ID is the key attribute of each row. Source is an attribute of ID. Source_description is an attribute of Source, but not ID.

But what does ID identify? Just the row? Or is it an identifier for a source?

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 14:37
Here's a simple graph demo.
![image](https://github.com/DDMAL/linkedmusic-datalake/assets/113382721/005afc8d-3689-43bf-bf44-116bc09c28d7)

**Comment by ahankinson** [comment] 2024-05-16 14:47
That doesn't answer my question. What does 1, 2, 3 identify? If it's just the row number in the CSV, why do you need it? That's irrelevant.

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 14:50
In the Chant CSV, for example, the ID represents the absolute_url, which identifies the reference of a particular chant. In a general case, it is the key identifier of each row.

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 14:51
> That doesn't answer my question. What does 1, 2, 3 identify? If it's just the row number in the CSV, why do you need it? That's irrelevant.

Can we move to slack? I think that would be more convenient.

**Comment by ahankinson** [comment] 2024-05-16 14:52
Yes, but then the conversation would get lost. @fujinaga may wish for the conversation to be recorded here?

**Comment by ahankinson** [comment] 2024-05-16 14:57
> In the Chant CSV, for example, the ID represents the absolute_url, which identifies the reference of a particular chant. In a general case, it is the key identifier of each row.

But that's two completely different things. 

In the CSV you have in front of you, the ID is an identifier for a chant. 

```
<http://example.com/chants/1  rdf:type  something:Chant>
<http://example.com/sources/1  contains http://example.com/chants/1>
<http://example.com/sources/1  contains http://example.com/chants/2>
<http://example.com/sources/1  wdt:description "My description">
```

Modelling lists in RDF is weird, but can be done. The "contains" bit in this example is a stand-in to illustrate that you can make a statement that this source contains these chants.

**Comment by Yueqiao12Zhang** [comment] 2024-05-16 15:20
![3891715872306_ pic](https://github.com/DDMAL/linkedmusic-datalake/assets/113382721/0e065b0d-4c34-4a7b-aa33-b3d7f1b4e717)

> But that's two completely different things.

> So in this case, each row identifies a chant. In another CSV, each row might identify a source, or a person, or a place. There is no "General case" where it is simply the identifier for a "row" -- it always identifies something that is of a specific type.

Yes, I definitely agree on this.
In this picture, the first column is an identifier for any chant, and there are a few attributes belonging to that chant including "source", which is an identifier for any source. However, the "source description" column is an attribute of a "source" but not a "chant", and there are two things of different types in a single row that need identification. 
The question is: if we want to process a CSV file like this, or even more complicated (more than one identifier of different types), how can we tell the program which subject to select when converting to turtle format?

**Comment by fujinaga** [comment] 2024-05-16 15:49
I'll explain further tomorrow; but basically, for each row, the first column is the identifier, all other columns are attributes for that identifier. We don't worry about if an entry in another column is another identifier or not. In RDF/Turtle, the first column becomes the Subject, the other entries becomes the Object, and the column header for that entry is the Predicate. It's very straightforward.

**Comment by candlecao** [comment] 2024-05-17 01:52
I read all above. I think if a RDB is converted into only one CSV files, there usually must be more than one entit(ies) with their own attributes. So I understand Yueqiao‘s concerns.

**Comment by candlecao** [comment] 2024-05-17 02:14
- More questions: In case of that a property has more than one value(s),what have you dealt with that? To copy the column for the property or to use something like semicolon to separate values in a cell?<br>
Etc.

- For a very "broad"(flattened) CSV file, we would like to know the "knowledge structure" of that from views of musicologists. That should be why Yueqiao wants to know the schema before specific coding task.

**Comment by ahankinson** [comment] 2024-05-17 07:49
> For a very "broad"(flattened) CSV file, we would like to know the "knowledge structure" of that from views of musicologists. That should be why Yueqiao wants to know the schema before specific coding task.

There are many knowledge structures from many different kinds of musicology. You cannot compare a Beethoven Symphony with a Gregorian Chant, and you can't compare a Rolling Stones recording with a Binding Fragment. This is why you shouldn't worry about the structure going in to the database... dump it in as "natively" as you can, and then try to make sense of it when you need to retrieve it. Then you can adjust your viewpoint to fit the data, and not have the data restricted by your viewpoint.

You cannot think that you first need to standardize the world. This has been tried many, many, many, many times before, with very little actual success. Either you end up with something so generic that it loses nuance (Dublin Core) or is extremely abstract and hard to apply for any given domain (CDOC CRM), or something so specific that it only really applies to a single domain and makes data analysis across domains impossible. 

**RDF can be boiled down to one simple idea: `X is Y`.** At any given point in your data, you can only make one single observation. You don't know the data structure beforehand, all you know is that you can make one statement

 - Beethoven is a person. 
 - Beethoven composed Symphony No. 9. 
 - Beethoven died in 1827. 

There is no model there, there are only observations and the RDF statements capture these observations. 

If you don't believe me, try to build a "model" for two different people in Wikidata. You will see that there is no "model" for person. You can have some properties that do or don't make sense for a person, but beyond that it's just a bunch of statements. A person and a dog can have the same life dates property, but don't John Cage doesn't need the "Animal Breed" property now, does he? 

 - https://www.wikidata.org/wiki/Q180727
 - https://www.wikidata.org/wiki/Q7126106

>  In case of that a property has more than one value(s),what have you dealt with that? 

It depends on what you want to do. You can make independent statements about them: "genre: Pop, Rock" -> "Song hasGenre Pop", "Song hasGenre Rock". Or you can use RDF lists or sets: https://ontola.io/blog/ordered-data-in-rdf

How you transport the data in CSV is irrelevant. CSV is only a convenience mechanism, and you could imagine that the data you import later may come from other types of "dumps": Web APIs, SQL databases, other Linked Data structures.

This is why it's better to deal with the data you have, and not try to over-engineer a "generic" solution to parsing these CSV files. There is no generic CSV.

**Comment by candlecao** [comment] 2024-05-21 13:14
Hello, @ahankinson. We really appreciate your sharing above views. Thank you. I think I got most of it. For some other things, we may talk later.

**Closed** 2024-11-05 16:46 UTC
Labels: hold
